const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('../app/node_modules/jsdom');const {loadAssetTracker}=require('./helpers/asset-tracker-harness');
function fixture(t){const dom=new JSDOM(fs.readFileSync(require.resolve('../index.html'),'utf8'));const listen=dom.window.document.addEventListener.bind(dom.window.document);dom.window.document.addEventListener=(name,...args)=>{if(name!=='DOMContentLoaded')listen(name,...args);};dom.window.HTMLCanvasElement.prototype.getContext=()=>({});const app=loadAssetTracker({document:dom.window.document});let created=0,destroyed=0;app.context.Chart=function(){created++;this.destroy=()=>{destroyed++;};};const tracker=new app.AssetTracker();tracker.data=tracker.getDefaultState();tracker.updateAnalyticsOptions();t.after(()=>{app.dispose();dom.window.close();});return {tracker,doc:dom.window.document,counts:()=>({created,destroyed})};}
test('all four analysis modes render old-web features and replace charts without retaining instances',t=>{const {tracker,doc,counts}=fixture(t);for(const [view,text] of [['trend','历史资产对比'],['spending','支出分类排行'],['forecast','周期现金流热区'],['structure','资产状态时间线']]){tracker.analyticsView=view;tracker.generateAnalytics();assert.match(doc.getElementById('analytics-output').textContent,new RegExp(text));}const c=counts();assert.equal(c.created-c.destroyed,doc.querySelectorAll('#analytics-output canvas:not([hidden])').length);});
test('malicious ledger names are displayed as plain text in analytics tables',t=>{const {tracker,doc}=fixture(t);tracker.data.categories={x:{id:'x',name:'<img src=x onerror=alert(1)>',balance:10,currency:'CNY'}};tracker.analyticsView='structure';tracker.generateAnalytics();assert.equal(doc.querySelector('#analytics-output img'),null);assert.match(doc.getElementById('analytics-output').textContent,/<img/);});
test('invalid scenario parameters show an actionable error without changing the ledger',t=>{const {tracker,doc}=fixture(t);const before=JSON.stringify(tracker.data);tracker.analyticsView='forecast';doc.getElementById('analytics-scenario-type').value='percentage';doc.getElementById('analytics-scenario-value').value='-100';tracker.generateAnalytics();assert.match(doc.getElementById('analytics-error').textContent,/-100/);assert.equal(JSON.stringify(tracker.data),before);});
test('historical rate save waits for persistence and does not change current exchange rates',async t=>{const {tracker,doc}=fixture(t);const rates=JSON.stringify(tracker.data.settings.exchangeRates);doc.getElementById('analytics-rate-currency').value='USD';doc.getElementById('analytics-rate-date').value='2026-01-01';doc.getElementById('analytics-rate-value').value='6.5';let resolve;tracker.persistData=()=>new Promise(r=>{resolve=r;});const saving=tracker.saveHistoricalAnalysisRate();assert.equal(doc.getElementById('analytics-rate-submit').disabled,true);assert.doesNotMatch(doc.getElementById('analytics-rate-error').textContent,/已保存/);resolve();await saving;assert.equal(JSON.stringify(tracker.data.settings.exchangeRates),rates);assert.match(doc.getElementById('analytics-rate-error').textContent,/已保存/);});
test('failed rate persistence remains locked and does not report success',async t=>{const {tracker,doc}=fixture(t);doc.getElementById('analytics-rate-currency').value='USD';doc.getElementById('analytics-rate-date').value='2026-01-01';doc.getElementById('analytics-rate-value').value='6.5';tracker.persistData=async()=>{throw Error('disk');};await tracker.saveHistoricalAnalysisRate();assert.match(doc.getElementById('analytics-rate-error').textContent,/未确认/);assert.equal(doc.getElementById('analytics-rate-submit').disabled,true);});
test('analysis export contains calculated data and does not write book state',async t=>{const {tracker}=fixture(t);let exported;tracker.fileAdapter.saveFile=async x=>{exported=x;};const before=JSON.stringify(tracker.data);await tracker.exportAnalyticsData();const data=JSON.parse(exported.text);assert.ok(Array.isArray(data.trend)&&Array.isArray(data.forecast));assert.equal(JSON.stringify(tracker.data),before);});
test('saving while on analytics refreshes the derived snapshot',t=>{const {tracker,doc}=fixture(t);doc.getElementById('analytics').classList.add('active');tracker.generateAnalytics();tracker.data={...tracker.data,categories:{cash:{id:'cash',name:'现金',balance:100,currency:'CNY'}}};tracker.updateDashboard();assert.equal(tracker.analyticsSnapshot.current.net,100);});
